### ISSUE TITLE
nb-skeleton does not work in a table

### ISSUE THREAD

**Issue by oldoldman** [nikbabchenko/skeleton-webcomponent#9]
I'm trying this web component in a table as follow , only the circle is rendered , the bar does not, what I'v missed , many thanks!!!
```html
<html lang='en'>
  <head>
    <meta charset='utf-8' />
    <script type="module" src="https://unpkg.com/skeleton-webcomponent-loader@1.0.5/dist/skeleton-webcomponent/skeleton-webcomponent.esm.js"></script>
  </head>
  <body>
    <table>
      <tr>
        <td>
          <nb-skeleton variant="circle"></nb-skeleton>
        </td>
        <td>
          <nb-skeleton height="10px"></nb-skeleton>
        </td>
      </tr>
    </table>
  </body>
</html>
```

**Comment by nikbabchenko** [comment]
@oldoldman, since it's the table it could take the full width, so if the width is not specified it's 100% but in table it's '0px'.

![image](https://user-images.githubusercontent.com/11876062/152316402-0ee18646-93f1-4c5b-96a4-4b2a77624937.png)

if you put the custom width it'll work 
for ex

```
     <nb-skeleton height="10px" width="100px"></nb-skeleton>
```

**Comment by oldoldman** [comment]
got it. thank you for your patience!
